### ISSUE TITLE
getClientRects vs getBoundingClientRect

### ISSUE THREAD

**Issue by yckart** [miguelmota/textnode-offset#1]
Is there a reason to use `getClientRects` instead of `getBoundingClientRect`? Are there any differences (or browser incompatibility) with `getBoundingClientRect`? I just found this: https://bugs.webkit.org/show_bug.cgi?id=46203

**Comment by miguelmota** [comment]
@yckart Updated it to use `getBoundingClientRect`. Thanks for bringing it up.
